---
title: "Project Scheme"
author: "Yiming Qian"
date: "`r Sys.Date()`"
output: html_document
---

***
## expected scheme:

| Project| idea developed |IRB| grant sumbitted|data collection|data analysis|conference| manuscript|submission|review|published|
| :---|     :---: | :---:|:---:|:---:|:---:|:---:|:---:|     ---:|
| **MOCO project.**  |[x]|[x]|[x]|[x]|[x]|[x]|[x]||||
|**R01 project.**| [x]|[x]|[x]|[x]|[x]||[x]||||
| ** Review paper (meta-analysis)**|
| ** the developing brain network with **| [x]||[x]|[x]||[x]||||
| **Townsend project.**| [x]|||||||||
| **Franco project.**| 


| **R01 project.**| tasks          |      deadline  | progress |
| :--------------       |:---------------------------------------------------------:|          :---:|   ---:|
| statistical analysis  |read script from Jiayi and Rick ("eye-tracking-DS", "Wilkinson-lab"), think of how to code    | Oct 14    |[x]|
|    | output data structure     | Nov 3    |[x]|
| abstract submission for Conference   | finish submission    | Dec 1    |[]|

| ** Review paper (meta-analysis)**| tasks          |      deadline  | progress |
| :--------------       |:---------------------------------------------------------:|          :---:|   ---:|
| literature review  | the goal for this review (infant/child/adult/animals, eeg/mri/behaviral)    | Nov  30, 2018   |[x]|
|    |collect the literature | Dec 11,2018    |[x]|
|    |read the literature | Jan 10, 2018   |[]|
|    |outline and propose an original idea  | Jan 11, 2018  |[]|
| Writing  |  | 2019  |[]|

| ** the developing brain network with **| tasks          |      deadline  | progress |
| :--------------       |:---------------------------------------------------------:|          :---:|   ---:|
| Attempt | read the paper for synthetic brain betwork, whether I can change a parameter | Nov 4, 2018   |[]|
| Brainstorm | generate the research question | NA  |[]|
|    |methodology | NA   |[]|
|    |what kind of data I want and how can I find the existed dataset | NA |[]|
|    |outline and propose an original idea  | NA  |[]|
| Writing  | write the proposal and prelimary analysis | Dec 4, 2018  |[]|

| **Townsend project.**| tasks          |      deadline  | progress |
| :--------------       |:---------------------------------------------------------:|          :---:|   ---:|
| experimental design  | think whether I can use motion for double factorial design    | Nov  17, 2018   |[]|
|    |staircase design | Nov 19, 2018     |[x]|
|    |brief proposal | Nov 29, 2018   |[x]|
|    |write the codes for experimental displays  | Dec 1, 2018  |[]|
| IRB   | submit the protocal for IRB  | Dec 1, 2018    |[]|
|   |  submit to SONA | Dec 7, 2019   |[]|

***
## Meetings with Suzy

For the Fall 2018 Semester, I met with Suzy at 1PM at her office on Nov 20, 2018 to talk about working in her lab. 

### 2018 Feb 1 Monday
- length: 70 min 
- location: Moore 115
- Agenda: 
    - copy the TD adolescents and adults data to the folder (see shard Evernote)
    - asked the experimental design questions
    - scheduled next meeting
    
### 2018 Jan 14 Monday
- length: 90 min 
- location: Moore 115
- Agenda: 
    - plan: 
      work on the ASD study with 24 adolescence and 24 adults (p/neutral/n face/animal face/objects)
        - pixal-magnitude
        - size- behavior
        - connnectivity
            - Pattern of connectivity
            - ED (R package Gimme)
            - graph theory metrics
      e.g. 1 bigger size of FFA, smaller ED
           2 FFA size
        yes  /      \?  (Yes for adult)
           Age----->CFMT
    - to do
       - read Whyte et al., 2015
       - schedule a meeting to check the subjects in the data and discuss about the predoctoral Autism Speaks
       - read the previous applicants for Autism Speaks, and check
          - range of funding (eye/behavioral/neuroimaging)
          - secondary data/ first-hand data collection
          - what is their goal: who want to develop skills/ deveote life to study ASD (You have skills. I want you incorporate it to study and make ASD population better)

### 2018 Nov 19 Monday
- length: 35 min 
- location: Moore 115
- Agenda: 
    - plan: 
        - working on the past dataset of DTI, fMRI or functional connectivity (choose one), to learn how to process these datasets
        - then we can sit together with RIck to discuss the next step, such as collaboration or ...
        - I expressed my interest to help with current projects, While Suzy said it still a long process before publishing paper. It is better for you to do sth which can be published soom
    - SO, I need to talk with Rick:
        - convey the content of this discussion with Suzy (timeline, the plan, my time management)
    - lab meeting: 1-2:15PM on Friday every two weeks, two left this semester, one dissertation by post-doc, one honor thesis by 2 undergrads.
    
***
## Meetings with Rick

For the Spring 2019, I will meet Rick on Fridays from 1-2 pm in Rick's office.
In some conditions, I may ask for extra meeting in the weekdays. 

### 2018 
### 2018 Feb 1 Monday
- length: 70 min 
- location: Moore 114
- Agenda: 
    - check Rick's manuscrip
    - graduate exhibition (past date)
    - to attend the conference, present the work and build the academic network. Rick said he do not know who will attend Linguistics and Cognitive Science Student Conference 2019
    
### 2019 Jan 15 Friday
- length:
- location: Moore 114
- question:
    - why do you say the motion sensitivity is underestimated in the experiments?
    - ICPSR Summer Program in Quantitative Methods of Social Research [https://www.icpsr.umich.edu/icpsrweb/content/sumprog/schedule.html]
    - summer course/schedule
    - graduate exhibition [https://secure.gradsch.psu.edu/cosign/registrations/gradexhibition/infosession/?utm_source=Graduate+Program+Contacts&utm_campaign=29808ba476-EMAIL_CAMPAIGN_2016_12_05_COPY_06&utm_medium=email&utm_term=0_8969d35e92-29808ba476-168543285]
    -  Linguistics and Cognitive Science Student Conference 2019 (Friday, April 12th, 2019) Deadline for abstract submission: February 28th, 2019 (by 5 pm EST)
- Agenda:

### 2019 Jan 15 Friday
- length:
- location: Moore 114
- Agenda:
    - summer: no more than 3 weeks vocation are good
    - drift diffusion model for MOCO
    - finish the r script and plot in R
    - email Andrea the experimental diagram in temple talk 2017-02-17 in github
    - new experiments:
        - measure motion (eye/object/head/body) empirically, get the speed distribution
        - 2 eye parameter
          3 head parameters
          3 body linear parameters
          3 body rotation parameters
        - get the parameters which is common at this age and use them to simulate the scene to see the noise sensitivity
    
### 2019 Jan 15 Friday
- length:
- location: Moore 114
- Agenda:
    - MOCO manuscript
-To do: 
    - ICPSR Summer Program in Quantitative Methods of Social Research [https://www.icpsr.umich.edu/icpsrweb/content/sumprog/schedule.html]
    - summer course/schedule
    - graduate exhibition [https://secure.gradsch.psu.edu/cosign/registrations/gradexhibition/infosession/?utm_source=Graduate+Program+Contacts&utm_campaign=29808ba476-EMAIL_CAMPAIGN_2016_12_05_COPY_06&utm_medium=email&utm_term=0_8969d35e92-29808ba476-168543285]

### 2019 Jan 11 Friday
- length:
- location: Moore 114
- Agenda:
    - MOCO manuscript
    - grant application:
      - Autism Speaks [https://science.grants.autismspeaks.org/uploads/helpdocs/2019%20Predoctoral_Fellowship_RFA.pdf]
      
### 2019 Jan 10 Friday
- length:
- location: Moore 114
- Agenda:
    - MOCO manuscript
    - neural network paper
    - grant application:
      - Autism Speaks [https://science.grants.autismspeaks.org/uploads/helpdocs/2019%20Predoctoral_Fellowship_RFA.pdf]
    - Reading this week
      - 2 paper
      - reading in course "Social development": How locomotion influence the perception, social cognition (Children start being able to differentiate the self from other in the world) and parent-child interaction

### 2019 Jan 4 Friday
- length: 74 min 
- location: Moore 114
- Agenda: 
    - give gifts
    - holiday greetings
    - course locomotion - balance your registered work with own research time (reading, thinking, writing, etc)
    - lab meeting -Wed
    - read 
        - Paper "Motion perception: a review of developmental changes and the role of early visual experience"
        - Paper "Identifying netural images from human brain activity"
        - Chapter "Looking with the head and eyes"
        - Check whether the chapter is worth reading in the lab meeting: "Perceiving Layout and knowing distances: the integration, relative potency, and contextual Use of Different Information about Depth"
    - Send the MOCO manuscript on Jan 11, Friday
    - Human vision (25 watz, more efficient) v.s. computer vision
        
### 2018 Nov 30 Friday
- length: 30 min 
- location: Moore 114
- Agenda: 
    - my prior meeting with Suzy
    - TAship
    - course in Spring 2018
        - Shall I take statistical course?
        - research thesis

### 2018 Nov 28 Wednesday
- length: 40 min 
- location: Moore 114
- Agenda: 
    - VSS (sned link to Krista)
    - TAship: Rick's course (Cannot find this course)
    - PsychoPy how to set luminance? Greyness
    - change lab meeting time to Friday 10AM-11PM
    - PC in the lab
    
### 2018 Nov 19 Monday
- length: 150 min 
- location: Ford 304
- Agenda: 
    - Spring 2019 subject pool screening 
        - Rich Carlson:  "If you would like to include a NEW instrument not previously included or submitted to the screening, I will need that instrument no later than **Thursday, December 7**, so that I can submit a modification to the IRB protocol for the screening.
    - a one-week NIH funded Summer Short Course (14-20 July 2019) titled "Interdisciplinary Training in Computational Neuroscience" 
        - The deadline for applications is 15 February 2019.  An on-line application form and additional details can be found in the attached flyer and at the website: https://engineering.missouri.edu/academics/eecs/neuro/neuro-outreach/neuro-brain/
    - my prior meeting with Suzy
    - TAship
    - course in Spring 2018
        - Shall I take statistical course?
        - research thesis
    - PsychoPy how to set luminance? 
    - IRB
  

### 2018 Nov 19 Monday
- length: 150 min 
- location: Ford 304
- Agenda: 
    - wilkinson lab
    - abstract for VSS as the first author
    - travel grants 
    - check the LP data of AC 

### 2018 Nov 17  (cancelled by snow)

### 2018 Nov 14 Wednesday (drop-in)
- length: 5 min
- location: moore 114
- Agenda: R01 project 2 analysis

### 2018 Nov 9 Friday
- length: 60 min 
- location: Moore 114
- Agenda: 
    - wilkinson lab, make plot, meeting request
    - Send the manuscript of MOCO next Wed to rick
    - read paper "navigating cognition: spatial codes for human" & "cognitive map in human and rats"
    - moving room experiment; human infants learn how to gaze in the first several months, how do they work with eye movement, body movement and head movement to adapt to the changing environment? Think out this
    - when you touch your eye, you feel your world move. But when you move your eye, you feel the world remain still. What's the mechanism behind it? Different pathways?
- Planned agenda for next meeting

### 2018 Nov 7 Wednesday (drop-in)
- length: 20 min
- location: moore 114
- Agenda:
    - Set up a regular check-in on Wednesday
    - Spring 2018, course
    - EEG softwares and protocal
        - brainvision analyzer
        - Power DIVA
    - Can I talk with Suzy? 
    - undergraduate progree
    - Krista R01 experiment: data analysis

### 2018 Nov 2 Friday
- length: 30 min 
- location: Moore 114
- Agenda: 
    - MOFO project used for constructing neural network for course PHYS 580
    - PLAY projects
    - Machine learning in CATlab
- Planned agenda for next meeting
    - [P.E.O. International Peace Scholarship](https://www.peointernational.org/ips-eligibility-requirements) 
        - Eligibility form due Dec 15; form due March 1
        - consent form: "Upon completion of my degree program(s) or Optional Practical Training (OPT) I hereby promise to return to my home country or to a location outside the United States or Canada within 60 days, depending on my visa status." 
    - Spring 2019 subject pool screening 
        - Rich Carlson:  If you would like to include a NEW instrument not previously included or submitted to the screening, I will need that instrument no later than **Thursday, December 7**, so that I can submit a modification to the IRB protocol for the screening.  
    ` SRCD coference in March, 2019 (WHen is the submission dadline?)
    - Suzy & Michael
  
### 2018-10-24 Wednesday
- length: 30 min 
- location: Moore 114
- Agenda: 
    - slack psu-psychology-forum: shall I invite other professors to the group? shall I invite all psychology students to the group?
    - reorganized the MOCO project in github
    - get Andrea's manuscripts: 
       - https://github.com/gilmore-lab/moco/blob/master/inf-2pat-lamrad/moco-inf-2pat-lamrad-manuscript2016.md (edited)
       - https://github.com/gilmore-lab/moco-psychophysics/blob/master/pubs/moco-child-laminar-radial-psychophysics-manuscript-2016.md
       - https://github.com/gilmore-lab/mofo/blob/master/child-tuning/pubs/mofo-child-manuscript2016.md
    - credit transfer
    - My intense interest in brain network, neuroimaging
    - list the author guides for the possible journals
    - how to add the references: 
        example: https://github.com/psu-psychology/r-bootcamp-2018/blob/master/talks/gilmore-hallquist-bootcamp-2018-papaja.Rmd
        1. add *.bib in the files; output: IO slide-presentaion or github_document
        2. papaja
        3. citr package

### 2018-10-19 Friday 
- length: 60 min 
- location: Moore 114
- Agenda: 
    - MOCO project
    - the project in wilkinson lab

### 2018-10-15 Monday (**Zoom!**)
- length: 55 min 
- Agenda: 
    - MOCO project
    
### 2018-10-12 Friday
- length: 15 min 
- Agenda: 
    - set the scheme for projects
    - MOCO project
    - publication protocols
    - socialization
    - the project in wilkinson lab
    - r consulting
- Next Meeting: Mon 4pm-5pm 
   